### ISSUE TITLE
请教下patch的时候勾选了shader相关的参数，mount后模型动画都正常唯独没有贴图是什么原因

### ISSUE THREAD

**Issue by mingxxming** [hxhb/HotPatcher#12]

**Comment by hxhb** [comment]
材质显示不正常？

**Comment by mingxxming** [comment]
就是没有贴图，差分pak 解出来看，贴图材质 shader都有的

**Comment by hxhb** [comment]
用以下方式排查一下：
1. 确认在热更之前出现问题的贴图没有被加载过
2. 在使用HotPatcher打包之前先执行一遍Cook生成新的shaderbytecode

**Comment by mingxxming** [comment]
1、模型贴图都是新导入项目的
2、确实有cook并且检查了saved 里的cooked文件
mount也是按照版本号依次mount。

**Comment by hxhb** [comment]
Log有资源加载错误的warning/error提示吗？

**Comment by mingxxming** [comment]
刚看了下确实有！
04-02 12:32:29.523 32412 32437 D UE4     : [2021.04.02-04.32.29:523][633]LogPakFile: New pak file /storage/emulated/0/Android/data/com.developdream.evh/files/Paks/1032.pak add
ed to pak precacher.
04-02 12:32:29.536 32412 32437 D UE4     : [2021.04.02-04.32.29:536][633]LogShaders: Error: Missing shader resource for hash 'C5B122ECB73B229DC2317207A4D8BEB60FB49E92' for sha
der platform 24 in the shader library
04-02 12:32:29.538 32412 32437 D UE4     : [2021.04.02-04.32.29:538][633]LogShaders: Error: Missing shader resource for hash 'F0A5360151DC6B2A2FB576621D239450D7FCA816' for sha
der platform 24 in the shader library
04-02 12:32:29.538 32412 32437 D UE4     : [2021.04.02-04.32.29:538][633]LogMaterial: Error: Tried to access an uncooked shader map ID in a cooked application
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:538][633]LogMaterial: Warning: Invalid shader map ID caching shaders for 'Material__5', will use default materi
al.
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:539][633]LogMaterial: Can't compile Material__5 with cooked content, will use default material instead
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:539][633]LogMaterial: Warning: [AssetLog] /Game/Actors/38/Material__5.Material__5: Failed to compile Material f
or platform GLSL_ES3_1_ANDROID, Default Material will be used in game.
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:539][633]LogMaterial: Error: Tried to access an uncooked shader map ID in a cooked application
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:539][633]LogMaterial: Warning: Invalid shader map ID caching shaders for 'Material__4', will use default materi
al.
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:539][633]LogMaterial: Can't compile Material__4 with cooked content, will use default material instead
04-02 12:32:29.539 32412 32437 D UE4     : [2021.04.02-04.32.29:539][633]LogMaterial: Warning: [AssetLog] /Game/Actors/38/Material__4.Material__4: Failed to compile Material f
or platform GLSL_ES3_1_ANDROID, Default Material will be used in game.

**Comment by mingxxming** [comment]
是要用 ShaderPatch 打补丁吗？  不是很明白ShaderPatch, 和 patch 的inlude shader bitcode 的设计区别。

**Comment by hxhb** [comment]
看到log了，你的这个问题是由于虽然你打包时包含了最新的shaderbytecode，但是还需要在热更之后加载一遍最新的shaderbytecode才可以读到最新的shader。
插件内提供了一个函数：`UFlibPatchParserHelper::ReloadShaderbytecode()`，mount之后调用一下即可。

**Comment by mingxxming** [comment]
非常感谢~
