### ISSUE TITLE
4.26.2 生成patch 的时候最后会出现一个崩溃窗口

### ISSUE THREAD

**Issue by machinesouls** [hxhb/HotPatcher#13]
4.26.2 生成patch 的时候最后会出现一个崩溃窗口，但是patch包是正确打包出来了

命令行模式下 直接报错，不能正确打包出来

编辑下和命令行模式打包Release 包都没有问题

**Comment by machinesouls** [comment]
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:323][  0]LogWindows: Error: === Critical error: ===
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:323][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:323][  0]LogWindows: Error: Fatal error!
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:323][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:323][  0]LogWindows: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000009ef998da0
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:324][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:324][  0]LogWindows: Error: [Callstack] 0x00007ffb5ea7da81 UE4Editor-HotPatcherEditor.dll!TSet<TTuple<FString,TArray<FPakFileInfo,TSizedDefaultAllocator<32> > >,TDefaultMapHashableKeyFuncs<FString,TArray<FPakFileInfo,TSizedDefaultAllocator<32> >,0>,FDefaultSetAllocator>::FindId() [D:\Program Files (x86
)\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Containers\Set.h:781]
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:324][  0]LogWindows: Error: [Callstack] 0x00007ffb5ea169fc UE4Editor-HotPatcherEditor.dll!<lambda_ff1551ee824053cad63d82b5b1330f89>::operator()() [D:\SVN_Local\CRRC\UE4_Project\InteractionSystem\Training\Plugins\HotPatcher\Source\HotPatcherEditor\Private\CreatePatch\PatcherProxy.cpp:626]
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:325][  0]LogWindows: Error: [Callstack] 0x00007ffb5ea2e0cb UE4Editor-HotPatcherEditor.dll!UE4Function_Private::TFunctionRefCaller<<lambda_ff1551ee824053cad63d82b5b1330f89>,void __cdecl(void)>::Call() [D:\Program Files (x86)\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Templates\Function.h:549]
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:325][  0]LogWindows: Error: [Callstack] 0x00007ffb7ea8bc7a UE4Editor-Core.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:325][  0]LogWindows: Error: [Callstack] 0x00007ffb7ea9ecdc UE4Editor-Core.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:325][  0]LogWindows: Error: [Callstack] 0x00007ffb7ea9f0ce UE4Editor-Core.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:325][  0]LogWindows: Error: [Callstack] 0x00007ffb7eab08fd UE4Editor-Core.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:325][  0]LogWindows: Error: [Callstack] 0x00007ffb87722b4d UE4Editor-RenderCore.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ffb8769732b UE4Editor-RenderCore.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ffb77246f81 UE4Editor-Engine.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ffb77237988 UE4Editor-Engine.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ff7e7e9056f UE4Editor-Cmd.exe!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ff7e7e91207 UE4Editor-Cmd.exe!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ff7e7e9125a UE4Editor-Cmd.exe!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ff7e7ea52bd UE4Editor-Cmd.exe!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:326][  0]LogWindows: Error: [Callstack] 0x00007ff7e7ea736e UE4Editor-Cmd.exe!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:327][  0]LogWindows: Error: [Callstack] 0x00007ffbd3ef7034 KERNEL32.DLL!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.04.28-09.39.41:327][  0]LogWindows: Error: [Callstack] 0x00007ffbd4be2651 ntdll.dll!UnknownFunction []
LogMissionNotificationProxy: Error: The Patch Mission is faild.

![image](https://user-images.githubusercontent.com/11766444/116382750-d33c7b00-a848-11eb-85a7-4be8d9cc2957.png)

**Comment by hxhb** [comment]
这是创建文件通知的时候crash了，patch已经生成完毕了，有时间我排查一下。

**Comment by hxhb** [comment]
你应该是编辑器模式执行的，standalone模式不会有这个错误。
