### ISSUE TITLE
Error when using encryption on patch

### ISSUE THREAD

**Issue by vinkumdev** [hxhb/HotPatcher#19]
`LogMissionNotificationProxy: Display: [2021.11.03-22.12.25:810][  0]LogHotPatcher: Display: Generating Pak list of Chunk 1.0.1.
LogMissionNotificationProxy: Display: [2021.11.03-22.12.25:816][  0]LogHotPatcherCommandlet: Display: Create Pak Commandline: %s: "C:/Users/tommy/Desktop/packaged/Windows/1.0.1/WindowsNoEditor/1.0.1_WindowsNoEditor_001_P.pak" -create="C:/Users/tommy/Desktop/packaged/Windows/1.0.1/WindowsNoEditor/1.0.1_WindowsNoEditor_001_P_PakCommands.txt" -AlignForMemoryM
apping=0 -compress -compressionformats=Zlib -encrypt -encryptindex -encryptionini -sign -projectdir="C:/Users/tommy/Documents/Unreal Projects/testproject/" -enginedir="D:/UnrealEngine/Engine/" -platform=Windows
LogMissionNotificationProxy: Warning: 1.03-22.12.25:819][  0]LogPakFile: Warning: A legacy command line syntax is being used for crypto config. Please update to using the -cryptokey parameter as soon as possible as this mode is deprecated
LogMissionNotificationProxy: Warning: 1.03-22.12.25:819][  0]LogOutputDevice: Warning:
LogMissionNotificationProxy: Display: Script Stack (0 frames):
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:440][  0]LogWindows: Error: === Critical error: ===
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:440][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:440][  0]LogWindows: Error: Assertion failed: SourceEngineConfigDir.EndsWith(L"Config/") [File:D:/UnrealEngine/Engine/Source/Runtime/Core/Private/Misc/ConfigCacheIni.cpp] [Line: 3632]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:440][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:440][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:440][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:441][  0]LogWindows: Error: [Callstack] 0x00007ffb4d9e4f99 KERNELBASE.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:441][  0]LogWindows: Error: [Callstack] 0x00007ffa786d9d56 UE4Editor-Core.dll!ReportAssert() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Windows\WindowsPlatformCrashContext.cpp:1616]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:441][  0]LogWindows: Error: [Callstack] 0x00007ffa786dd508 UE4Editor-Core.dll!FWindowsErrorOutputDevice::Serialize() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Windows\WindowsErrorOutputDevice.cpp:78]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:441][  0]LogWindows: Error: [Callstack] 0x00007ffa783ee74d UE4Editor-Core.dll!FOutputDevice::LogfImpl() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Misc\OutputDevice.cpp:61]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:441][  0]LogWindows: Error: [Callstack] 0x00007ffa78385095 UE4Editor-Core.dll!AssertFailedImplV() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:104]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:441][  0]LogWindows: Error: [Callstack] 0x00007ffa78387130 UE4Editor-Core.dll!FDebug::CheckVerifyFailedImpl() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:461]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:442][  0]LogWindows: Error: [Callstack] 0x00007ffa78380e81 UE4Editor-Core.dll!FConfigFile::AddStaticLayersToHierarchy() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Misc\ConfigCacheIni.cpp:3632]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:442][  0]LogWindows: Error: [Callstack] 0x00007ffa7839f8c0 UE4Editor-Core.dll!FConfigCacheIni::LoadExternalIniFile() [D:\UnrealEngine\Engine\Source\Runtime\Core\Private\Misc\ConfigCacheIni.cpp:4064]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:442][  0]LogWindows: Error: [Callstack] 0x00007ffa778f4762 UE4Editor-PakFileUtilities.dll!LoadKeyChain() [D:\UnrealEngine\Engine\Source\Developer\PakFileUtilities\Private\PakFileUtilities.cpp:1646]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:442][  0]LogWindows: Error: [Callstack] 0x00007ffa778e5ff9 UE4Editor-PakFileUtilities.dll!ExecuteUnrealPak() [D:\UnrealEngine\Engine\Source\Developer\PakFileUtilities\Private\PakFileUtilities.cpp:4869]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:442][  0]LogWindows: Error: [Callstack] 0x00007ffaac7b87d0 UE4Editor-HotPatcherEditor.dll!<lambda_5b3b7089ea35ba72bfd8d70e8bdcbc26>::operator()() [C:\Users\tommy\Documents\Unreal Projects\testproject\Plugins\HotPatcher\Source\HotPatcherEditor\Private\CreatePatch\PatcherProxy.cpp:1024]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:442][  0]LogWindows: Error: [Callstack] 0x00007ffaac7dde8b UE4Editor-HotPatcherEditor.dll!UE4Function_Private::TFunctionRefCaller<<lambda_5b3b7089ea35ba72bfd8d70e8bdcbc26>,void __cdecl(void)>::Call() [D:\UnrealEngine\Engine\Source\Runtime\Core\Public\Templates\Function.h:549]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:443][  0]LogWindows: Error: [Callstack] 0x00007ffaac7c0ade UE4Editor-HotPatcherEditor.dll!UE4Function_Private::TFunctionRefBase<UE4Function_Private::TFunctionStorage<0>,void __cdecl(void)>::operator()() [D:\UnrealEngine\Engine\Source\Runtime\Core\Public\Templates\Function.h:677]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:443][  0]LogWindows: Error: [Callstack] 0x00007ffaac8ab83a UE4Editor-HotPatcherEditor.dll!FThreadWorker::Run() [C:\Users\tommy\Documents\Unreal Projects\testproject\Plugins\HotPatcher\Source\HotPatcherEditor\Public\ThreadUtils\FThreadUtils.hpp:50]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:443][  0]LogWindows: Error: [Callstack] 0x00007ffaac80dac6 UE4Editor-HotPatcherEditor.dll!PatchWorker::CreatePakWorker() [C:\Users\tommy\Documents\Unreal Projects\testproject\Plugins\HotPatcher\Source\HotPatcherEditor\Private\CreatePatch\PatcherProxy.cpp:1057]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:444][  0]LogWindows: Error: [Callstack] 0x00007ffaac7ddbda UE4Editor-HotPatcherEditor.dll!UE4Function_Private::TFunctionRefCaller<bool (__cdecl*)(FHotPatcherPatchContext &),bool __cdecl(FHotPatcherPatchContext &)>::Call() [D:\UnrealEngine\Engine\Source\Runtime\Core\Public\Templates\Function.h:540]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:444][  0]LogWindows: Error: [Callstack] 0x00007ffaac7c0bdf UE4Editor-HotPatcherEditor.dll!UE4Function_Private::TFunctionRefBase<UE4Function_Private::TFunctionStorage<0>,bool __cdecl(FHotPatcherPatchContext &)>::operator()() [D:\UnrealEngine\Engine\Source\Runtime\Core\Public\Templates\Function.h:677]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:444][  0]LogWindows: Error: [Callstack] 0x00007ffaac819d86 UE4Editor-HotPatcherEditor.dll!UPatcherProxy::DoExport() [C:\Users\tommy\Documents\Unreal Projects\testproject\Plugins\HotPatcher\Source\HotPatcherEditor\Private\CreatePatch\PatcherProxy.cpp:182]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:444][  0]LogWindows: Error: [Callstack] 0x00007ffaac8679ef UE4Editor-HotPatcherEditor.dll!UHotPatcherCommandlet::Main() [C:\Users\tommy\Documents\Unreal Projects\testproject\Plugins\HotPatcher\Source\HotPatcherEditor\Classes\Commandlets\HotPatcherCommandlet.cpp:125]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:445][  0]LogWindows: Error: [Callstack] 0x00007ff600269329 UE4Editor-Cmd.exe!FEngineLoop::PreInitPostStartupScreen() [D:\UnrealEngine\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:3369]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:445][  0]LogWindows: Error: [Callstack] 0x00007ff60026089d UE4Editor-Cmd.exe!GuardedMain() [D:\UnrealEngine\Engine\Source\Runtime\Launch\Private\Launch.cpp:127]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:445][  0]LogWindows: Error: [Callstack] 0x00007ff600260bfa UE4Editor-Cmd.exe!GuardedMainWrapper() [D:\UnrealEngine\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:445][  0]LogWindows: Error: [Callstack] 0x00007ff600274add UE4Editor-Cmd.exe!WinMain() [D:\UnrealEngine\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:445][  0]LogWindows: Error: [Callstack] 0x00007ff600276b82 UE4Editor-Cmd.exe!__scrt_common_main_seh() [D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:446][  0]LogWindows: Error: [Callstack] 0x00007ffb4e337034 KERNEL32.DLL!UnknownFunction []
LogMissionNotificationProxy: Error: [2021.11.03-22.12.47:446][  0]LogWindows: Error: [Callstack] 0x00007ffb4fc82651 ntdll.dll!UnknownFunction []`

**Comment by hxhb** [comment]
Fixed in [2ab59d83](https://github.com/hxhb/HotPatcher/commit/2ab59d83f900cf94c96cacc6916a7693970a072d).
