### ISSUE TITLE
[Crash] MacOS 4.26.2 版本点击 crash

### ISSUE THREAD

**Issue by zyfu0000** [hxhb/HotPatcher#21]
![Screen Shot 2021-11-30 at 9 19 46 PM](https://user-images.githubusercontent.com/2409591/144058440-8f76195b-1962-495e-a885-7a1037fc96ba.jpg)

**Comment by hxhb** [comment]
fixed in [d3a31f186](https://github.com/hxhb/HotPatcher/commit/d3a31f186042720a09ab960688515888a28f6fe7)
