### ISSUE TITLE
4.24版本在IOS平台进行加载含有动画序列的pak时，程序闪退。求大佬帮助一下。谢谢。

### ISSUE THREAD

**Issue by mki2301** [hxhb/HotPatcher#22]
在4.24打包的IOS下进行动态加载引用动画序列（AnimationSequence）的蓝图类的pak时（被引用的动画序列的相关一起打进了pak包里），程序闪退。我看了一下日志，刚好就在执行LoadClass()这一步的时候崩了。这个情况在4.26的安卓运行时也会出现。但是4.24和4.26的windows都能正常加载运行。然后我进行了一些尝试，发现动画序列里依赖了引擎的两个压缩设置。在4.26里
是图片1，我将这两个依赖项复制到当前路径下，并且把动画序列的依赖项改为当前目录下的，再进行打包pak。结果4.26的安卓就能正常加载运行了 。然后我想用同样的方法对4.24的进行改动，但是发现4.24动画序列的两个依赖项和4.26的不一样。如图2
。并且4.24的这个压缩模式的依赖好像改不了。我就彻底没办法了。麻烦帮忙看一下。谢谢了
![b028b01114841b980f19d86fcba838b](https://user-images.githubusercontent.com/66762883/144966538-e8f1a7c5-cf88-41b2-950a-2b4b57571e33.png)
![a1e6bfcbb3ebac515ac521e68f1cd5f](https://user-images.githubusercontent.com/66762883/144967238-2c633d88-c40d-4002-873e-26bcab351023.png)

**Comment by hxhb** [comment]
附上具体的报错Log.

**Comment by mki2301** [comment]
![419a6ac1a5431bcc635bb904a8cea76](https://user-images.githubusercontent.com/66762883/144972816-ee986ac1-17bd-4d81-abe1-8bd356a30ed6.jpg)
![ece7d62024a13ffd7d67056f9c27bcb](https://user-images.githubusercontent.com/66762883/144972836-492c5648-0f32-4d27-9d0b-12aeeb50aaa6.png)

图1是log日志，图2是动态加载的代码 @hxhb

**Comment by hxhb** [comment]
你发的log里没有crash部分的log，建议把完整的log发上来。

**Comment by mki2301** [comment]
进程的日志到这里就没了。就是因为没有Log，我是真的毫无办法。我是在Mac上进行的调试，看的日志。还有一个就是ios系统自己的reportcrash。我也贴上来。但是感觉没啥用
<img width="1866" alt="59e1234aecf547817521f9279319c6f" src="https://user-images.githubusercontent.com/66762883/145145900-6071c394-1256-427d-92b3-252247ba60b5.png">

我利用android studio还原了之前在安卓平台上的现象。然后报错的日志是类似这样的:
LogStreaming: Error: Couldn't find file for package /Engine/Animation/DefaultAnimCurveCompressionSettings requested by async loading code. NameToLoad: /Engine/Animation/DefaultAnimCurveCompressionSettings.
LogStreaming: Error: This will hitch streaming because it ends up searching the disk instead of finding the file in the pak file.
我怀疑目前IOS遇到的问题可能也是这个，但是我不知道怎么去解决

**Comment by hxhb** [comment]
> 进程的日志到这里就没了。就是因为没有Log，我是真的毫无办法。我是在Mac上进行的调试，看的日志。还有一个就是ios系统自己的reportcrash。我也贴上来。但是感觉没啥用 <img alt="59e1234aecf547817521f9279319c6f" width="1866" src="https://user-images.githubusercontent.com/66762883/145145900-6071c394-1256-427d-92b3-252247ba60b5.png">
> 
> 我利用android studio还原了之前在安卓平台上的现象。然后报错的日志是类似这样的: LogStreaming: Error: Couldn't find file for package /Engine/Animation/DefaultAnimCurveCompressionSettings requested by async loading code. NameToLoad: /Engine/Animation/DefaultAnimCurveCompressionSettings. LogStreaming: Error: This will hitch streaming because it ends up searching the disk instead of finding the file in the pak file. 我怀疑目前IOS遇到的问题可能也是这个，但是我不知道怎么去解决

你单独把` /Engine/Animation/DefaultAnimCurveCompressionSettings`这个资源添加到Patch资源的列表里再试试。

**Comment by mki2301** [comment]
添加到patch资源列表？意思就是把这个资源放到打pak包的资源目录下然后引用此目录下的/Engine/Animation/DefaultAnimCurveCompressionSettings这个东西，然后再一起打进pak包里？4.26安卓我就是这么干的，把两个引擎资源都放进去，然后就可以成功加载了。但是在4.24里。引用的两个资源。DefaultAnimCurveCompressionSettings是一样的。但是另外一个不一样，在4.24里另外一个是图中所示的AnimCompressBitwiseCompressOnly在编辑器里根本就找不着。并且都不能去替换成其他引用
![BBTZR E_IU08 6~{L@`P_ 6](https://user-images.githubusercontent.com/66762883/145148203-142b68c9-591d-473c-88a4-78a3b0c64a6b.png)

**Comment by mki2301** [comment]
大佬还在吗

**Comment by hxhb** [comment]
你log里提示加载失败的是`/Engine/Animation/DefaultAnimCurveCompressionSettings`这个资源，不是你图里截的`AnimCompressBitwiseCompressOnly`

**Comment by mki2301** [comment]
IOS是4.24，没有相关的日志。这个日志是4.26的安卓上面的。这两个端出现的现象都是一样的。并且都是执行到LoadClass()函数时闪退。所以我猜测应该是同一个原因。至于截图里的和日志里的资源，这两个都是引擎资源。4.26安卓里DefaultAnimCurveCompressionSettings，DefaultAnimBoneCompressionSettings这两个资源都报错了的。在4.24里，Curve Compression Settings曲线压缩设置DefaultAnimCurveCompressionSettings与4.26一样。但是另外一个资源在4.24里是Compression Scheme(压缩模式)：AnimCompressBitwiseCompressOnly。在4.26里是Bone Compression Settings骨骼压缩模式：DefaultAnimBoneCompressionSettings

**Comment by mki2301** [comment]
所以我怀疑是项目设置哪里不对，因为按道理来说引擎原生的资源应该是一起打到程序里面的，为什么就找不这呢。

**Comment by hxhb** [comment]
@mki2301 我给插件提供了一个PackageTracker的功能，可以追踪到动画序列的`BoneCompressionSettings `和`CruveCompressionSettings `的资源，你可以更新dev分支之后再重新测试一下。
