### ISSUE TITLE
UE 4.27.1改动userwidget后打补丁没有成功打进去。

### ISSUE THREAD

**Issue by aimercat** [hxhb/HotPatcher#23]
解包发现userwidget资源没有打进去，比较release.josn里的Guid发现Guid是一致的，请问大佬有什么解决办法.HotPatcher用的V72.
官方源码写的Guid要被废弃了。。。
![image](https://user-images.githubusercontent.com/42489051/147235392-65c951c3-ccf1-4afe-9bee-b0dda62070a3.png)

**Comment by hxhb** [comment]
废弃也没关系的，后面我会在插件中实现一个单独的GUID计算方式，不再依赖UE的PackageGUID。

**Comment by hxhb** [comment]
> 废弃也没关系的，后面我会在插件中实现一个单独的GUID计算方式，不再依赖UE的PackageGUID。

[v73](https://github.com/hxhb/HotPatcher/releases/tag/v73)中已支持，但默认未开启，准备等到UE把它正式废弃之后再开启，现在你可以根据需求控制`CUSTOM_ASSET_GUID`启用。

**Comment by aimercat** [comment]
谢谢大佬
