### ISSUE TITLE
关于RecursiveWidgetTree字段的问题

### ISSUE THREAD

**Issue by a770931435** [hxhb/HotPatcher#24]
测试环境：UE4 4.25引擎，插件版本：V73
大佬你好，我目前遇到了UMG子控件热更不生效的问题。
问题1：
我有个工程，有UMG MainUI和SubA两个蓝图，MainUI由LevelBP创建显示，SubA是直接挂在Main上面。引用关系如图。
![image](https://user-images.githubusercontent.com/13850406/147848329-a4ab4f28-8307-4bc5-8fbc-d1d4b9f4fce5.png)
此时，讲道理，我修改SubA的内容，仅对SubA进行pak和热更，游戏内并不会实际生效，而带上Main连同SubA一起Pak，热更新就可以成功。
大佬对此类问题给的解法是在By patch时勾选RecursiveWidgetTree，我这边，仅修改SubA的内容，勾选后RecursiveWidgetTree，发现依旧只打了SubA
![image](https://user-images.githubusercontent.com/13850406/147848349-a3808f57-1c25-4d74-87f5-23f5a3a211f5.png)
是我的设置哪里出错了吗？

问题2：
我发现不止是UMG子控件，可能其他的子控件也有类似问题，比如一个蓝图引用了一个mesh，只pak这个蓝图后，提示mesh丢失，RecursiveWidgetTree是支持所有资源（不止是UMG蓝图）引用查询和自动化添加到pak列表的吗？

**Comment by hxhb** [comment]
开启资源的依赖分析就可以了，UMG RecursiveWidgetTree没生效的问题，可以把你具体的配置发过来或者提供一份可复现的工程。

**Comment by hxhb** [comment]
@a770931435 RecursiveWidgetTree的问题大概看了一下，确实在高版本引擎中有问题，有时间我修复一下。

**Comment by hxhb** [comment]
@a770931435 我在dev分支修复了，更新dev重试即可。

**Comment by a770931435** [comment]
Hello，首先非常感谢大佬在百忙之余给予问题修复，这里送上迟来的元旦祝福，大佬元旦快乐，工作辛苦了。

目前我尝试更新到dev分支的最新后，发现依旧不生效，我不太清楚是哪里出了问题，我把工程链接贴上来了，大佬什么时候有空可以帮忙看一下。我在工程里描述了问题复现方法。

github链接：https://github.com/a770931435/HotPatchDemo

或者可以使用
百度网盘
链接：https://pan.baidu.com/s/1SFIr246QieN7LIM0IC-uhA 
提取码：oflv

**Comment by hxhb** [comment]
@a770931435 我看了你的描述，不要使用这里的Cook，这是UE默认的CookCommandlet，可能与Patch的资源无法对齐。

![image](https://user-images.githubusercontent.com/12034244/147869096-3083bc58-6730-4572-b2ae-9726116c222b.png)

解决办法是勾选Patch配置中的bCookPatchAssets即可。

**Comment by a770931435** [comment]
hello 
我尝试勾选bCookPatchAssets 查看了下PreviewPatch，依旧没拿到真正的引用了Main的那个Core/UI/UMG_Main
如图
![企业微信截图_16411104502584](https://user-images.githubusercontent.com/13850406/147869714-4187434b-4348-47c8-a241-e77d7d4d5e9b.png)
![企业微信截图_16411106213665](https://user-images.githubusercontent.com/13850406/147869786-9d053ccd-bdd4-49be-bde5-9e615aef1539.png)

配置如图
![企业微信截图_16411107366956](https://user-images.githubusercontent.com/13850406/147869820-715200cf-a72c-4a9d-ad8c-2e5e6030b9ea.png)

**Comment by hxhb** [comment]
没复现你说的情况，最好是直接生成看生成的结果：
![image](https://user-images.githubusercontent.com/12034244/147869964-2c1f7aa1-6d97-4552-87a7-32c424675098.png)

![image](https://user-images.githubusercontent.com/12034244/147869986-f1d96834-d928-41a7-86d8-24abd485ae44.png)

**Comment by a770931435** [comment]
我这边生成出来的是这样的，的确没用把那个未被修改但是应该被带进来的Core/UI/UMG_Main打进去
![image](https://user-images.githubusercontent.com/13850406/147870182-51cc6bfe-1313-4536-b747-ef606f6019ce.png)

我的这个问题在我给你的那个git链接里是必现的，而且我创建任何的空工程，这个问题都可以必现，如果您那边无法复现，我觉得可能跟我本地开发环境有点关系。

我本地是UE4 4.25.4 VS2019 HotPatcherV73 dev最新

大佬您那边UE4的版本是什么样的呀，我再确认下是不是版本导致的，先保证开发环境和您一致然后我再尝试处理。

**Comment by hxhb** [comment]
@a770931435 我用你分享的demo里，也是可以的，我本地没有4.25的引擎版本 用的是4.26。
![image](https://user-images.githubusercontent.com/12034244/147870306-1c2c731c-5c7f-4c83-81e1-b9cc7816e5a1.png)

**Comment by a770931435** [comment]
好的 我先安装一下4.26版本看一下这个问题还在不

**Comment by a770931435** [comment]
@hxhb  大佬 我本地尝试UE4.26 依旧存在这个问题，能提供一下您针对我分享的demo的byPatch的PatchConfig.json嘛？我觉得应该是我配置漏掉了什么内容。

**Comment by a770931435** [comment]
我尝试注释掉这段代码，就可以达到前置引用查找的目的了
![企业微信截图_16411156651665](https://user-images.githubusercontent.com/13850406/147871736-bf05a2d8-5465-4738-82e1-40fdefc0d46a.png)
![企业微信截图_16411156703160](https://user-images.githubusercontent.com/13850406/147871737-61086f7d-8c54-45cb-8bd5-024ea0f3e820.png)

**Comment by hxhb** [comment]
你是开启了版本比对的？这种情况确实会有问题，我晚点优化一下。

**Comment by a770931435** [comment]
是的，开启了版本比对的。
byPatch是基于byRelease生成的Release.json，填写到BaseVersion的进行patch的。
期待大佬的修复，非常感谢。

**Comment by hxhb** [comment]
@a770931435 已修复，提交依然在dev分支，目前`bRecursiveWidgetTree`的规则为：
1. 若没有指定基础版本，则默认递归分析Patch中UMG资源的所有引用它的父级UMG控件
2. 若指定基础版本，只会分析基础包中存在的父级UMG控件，避免带入非必要资源

**Comment by a770931435** [comment]
验证了下，没有问题了，感谢大佬协助。辛苦了！
