### ISSUE TITLE
v74版本打补丁包断言失败

### ISSUE THREAD

**Issue by stlnkm** [hxhb/HotPatcher#26]
打热更包出现下面的断言失败：
![image](https://user-images.githubusercontent.com/1908920/148726859-8d5d2d5d-9637-4e7d-a4f6-4752385bb5a9.png)

可能相关的配置如下：
![image](https://user-images.githubusercontent.com/1908920/148726728-1a82c83e-23f2-4272-929f-832d936fd5f5.png)

经二分排除定位法确定导致问题的提交记录如下：
![image](https://user-images.githubusercontent.com/1908920/148726951-ff46eccb-167a-41d2-b501-8f734b914a11.png)

**Comment by stlnkm** [comment]
[PatchConfig.zip](https://github.com/hxhb/HotPatcher/files/7837224/PatchConfig.zip)

**Comment by hxhb** [comment]
把`bSerializeAssetRegistry`关掉看看还有没有其他问题。

**Comment by hxhb** [comment]
@stlnkm 已定位到问题，是由于工程中存在重定向器，导致向State写入相同资源引起的。

**Comment by hxhb** [comment]
@stlnkm 更新最新的dev分支即可，过段时间会合并到主干分支v75版本。

**Comment by stlnkm** [comment]
> @stlnkm 更新最新的dev分支即可，过段时间会合并到主干分支v75版本。

好的，AssetRegistry对我是必须的，因为存在手动加载的PrimaryAsset。
