### ISSUE TITLE
4.23.1版本插件FMemory::Memcpy()函数报错

### ISSUE THREAD

**Issue by HSHSir** [hxhb/HotPatcher#32]
最新4.23版本API变动了,需改一下插件代码
![QQ图片20220206135302](https://user-images.githubusercontent.com/61901106/152669451-287a2e04-7a30-41fe-9984-71f4365683fa.png)

**Comment by hxhb** [comment]
fixed in [88d41a27](https://github.com/hxhb/HotPatcher/commit/88d41a27d8f4166b7040ba92435863e605df1af9)
