### ISSUE TITLE
UE4.27 cook content 时候会直接崩溃

### ISSUE THREAD

**Issue by houmy110** [hxhb/HotPatcher#38]
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000000000000003e

UE4Editor_Core
UE4Editor_HotPatcherEditor!TArray<FString,TSizedDefaultAllocator<32> >::CopyToEmpty<FString,int>() [D:\UE4\UE_4.27\Engine\Source\Runtime\Core\Public\Containers\Array.h:2652]
UE4Editor_HotPatcherEditor!TArray<FString,TSizedDefaultAllocator<32> >::operator=() [D:\UE4\UE_4.27\Engine\Source\Runtime\Core\Public\Containers\Array.h:441]
UE4Editor_HotPatcherEditor!FOriginalCookerContext::GetCookConfig() [D:\ue4_project\HotPatcherProject\Plugins\HotPatcher\Source\HotPatcherEditor\Public\Model\FOriginalCookerContext.h:204]
UE4Editor_HotPatcherEditor!SOriginalCookWidget::RunCook() [D:\ue4_project\HotPatcherProject\Plugins\HotPatcher\Source\HotPatcherEditor\Private\Cooker\OriginalCooker\SOriginalCookWidget.cpp:230]
UE4Editor_HotPatcherEditor!UE4Tuple_Private::TTupleBase<TIntegerSequence<unsigned int> >::ApplyAfter<FReply (__cdecl SOriginalCookWidget::*const &)(void)const ,SOriginalCookWidget * &>() [D:\UE4\UE_4.27\Engine\Source\Runtime\Core\Public\Templates\Tuple.h:306]
UE4Editor_HotPatcherEditor!TBaseSPMethodDelegateInstance<1,SOriginalCookWidget const ,0,FReply __cdecl(void),FDefaultDelegateUserPolicy>::Execute() [D:\UE4\UE_4.27\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:290]
UE4Editor_Slate

**Comment by hxhb** [comment]
在最新的版本中已修复。
