### ISSUE TITLE
UE5 Linux Case Sensitive File System Build Error

### ISSUE THREAD

**Issue by deathlyrage** [hxhb/HotPatcher#42]
Building against Unreal Engine 5.0 release with Linux. I think unreal engine renamed this file so we would have to add a #if ENGINE VERSION MAJOR == 5 then use a capital M in the include.

`
In file included from /home/user/workspace/pot/pot-UE5/Game/Plugins/HotPatcher/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/HotPatcherCore/Module.HotPatcherCore.gen.cpp:9:
In file included from /home/user/workspace/pot/pot-UE5/Game/Plugins/HotPatcher/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Inc/HotPatcherCore/GameFeatureProxy.gen.cpp:8:
In file included from /home/user/workspace/pot/pot-UE5/Game/Plugins/HotPatcher/Source/HotPatcherCore/Public/GameFeature/GameFeatureProxy.h:6:
In file included from /home/user/workspace/pot/pot-UE5/Game/Plugins/HotPatcher/Source/HotPatcherCore/Public/CreatePatch/HotPatcherProxyBase.h:5:
In file included from /home/user/workspace/pot/pot-UE5/Game/Plugins/HotPatcher/Source/HotPatcherRuntime/Public/CreatePatch/HotPatcherContext.h:12:
[1m/home/user/workspace/pot/pot-UE5/Game/Plugins/HotPatcher/Source/HotPatcherRuntime/Public/BaseTypes/FPackageTracker.h:5:10: [0m[0;1;31mfatal error: [0m[1m'HAL/PlatformFilemanager.h' file not found[0m
#include "HAL/PlatformFilemanager.h"
[0;1;32m         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m1 error generated.
`

**Comment by hxhb** [comment]
At present, I have not adapted to the official version of UE5, there may be some problems.
