### ISSUE TITLE
对于UE5正式版本还会支持吗

### ISSUE THREAD

**Issue by SKZXstudio** [hxhb/HotPatcher#52]
我之前使用UE5.0.1的时候我的安卓项目无法打包
排查了一圈发现主页上写着不支持正式版，不知道当前版本是否已经静默支持，如果支持了作者方便回复一下最好
现在正式版已经更新了3个小版本了，应该算是比较稳定了，不知道作者有没有支持正式版的想法

**Comment by hxhb** [comment]
目前仍不支持正式版，适配在计划当中。

**Comment by hxhb** [comment]
[dev](https://github.com/hxhb/HotPatcher/tree/dev)分支已支持。

**Comment by SKZXstudio** [comment]
感谢您的回复以及您的付出！辛苦了！发自我的 iPhone在 2022年9月6日，10:44，lipengzha ***@***.***> 写道：﻿
dev分支已支持。
