### ISSUE TITLE
4.21版本by release打包会报错，4.26版本正常。使用hot patcher版本75.2&76.1

### ISSUE THREAD

**Issue by ojo909023661** [hxhb/HotPatcher#57]
LogMissionNotificationProxy: Display: [2022.08.26-03.17.59:523][  0]LogTemp: Display: Loaded TP LinuxTargetPlatform
LogMissionNotificationProxy: Display: [2022.08.26-03.17.59:578][  0]LogTemp: Display: Loaded TP LuminTargetPlatform
LogMissionNotificationProxy: Display: [2022.08.26-03.17.59:578][  0]LogTemp: Display: Loaded TP LuminTargetPlatform
LogMissionNotificationProxy: Display: [2022.08.26-03.17.59:578][  0]LogTargetPlatformManager: Display: Building Assets For Windows
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: === Critical error: ===
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: Assertion failed: bInitialized [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\ShaderCore\Private\ShaderCore.cpp] [Line: 241]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: GShaderHashCache::Initialize needs to be called before GShaderHashCache::GetPlatformIncludeDirectory.
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error:
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffe361c4f69 KERNELBASE.dll!UnknownFunction []
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde5d9cd1a UE4Editor-Core.dll!FWindowsErrorOutputDevice::Serialize() [d:\build\++ue4\sync\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:63]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde5b7a967 UE4Editor-Core.dll!FOutputDevice::LogfImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde5ab0df7 UE4Editor-Core.dll!FDebug::AssertFailed() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:417]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde7f8e69c UE4Editor-ShaderCore.dll!FShaderHashCache::ShouldIgnoreInclude() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:201]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde7f428e1 UE4Editor-ShaderCore.dll!GetShaderIncludes() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:714]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde7f42925 UE4Editor-ShaderCore.dll!GetShaderIncludes() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:719]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde7f42925 UE4Editor-ShaderCore.dll!GetShaderIncludes() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:719]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:372][  0]LogWindows: Error: [Callstack] 0x00007ffde7f42925 UE4Editor-ShaderCore.dll!GetShaderIncludes() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:719]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ffde7f1947a UE4Editor-ShaderCore.dll!AddShaderSourceFileEntry() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:411]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ffde7f3cf71 UE4Editor-ShaderCore.dll!GetAllVirtualShaderSourcePaths() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:432]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ffde7f25208 UE4Editor-ShaderCore.dll!BuildShaderFileToUniformBufferMap() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:875]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ffde7f4ae21 UE4Editor-ShaderCore.dll!InitializeShaderTypes() [d:\build\++ue4\sync\engine\source\runtime\shadercore\private\shadercore.cpp:948]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ff6a224cf57 UE4Editor-Cmd.exe!FEngineLoop::PreInit() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:1941]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ff6a2245783 UE4Editor-Cmd.exe!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:135]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ff6a22459ea UE4Editor-Cmd.exe!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ff6a22548da UE4Editor-Cmd.exe!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:276]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:373][  0]LogWindows: Error: [Callstack] 0x00007ff6a225584e UE4Editor-Cmd.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:456][  0]LogWindows: Error: [Callstack] 0x00007ffe37817034 KERNEL32.DLL!UnknownFunction []
LogMissionNotificationProxy: Error: [2022.08.26-03.18.03:456][  0]LogWindows: Error: [Callstack] 0x00007ffe389a2651 ntdll.dll!UnknownFunction []
LogMissionNotificationProxy: Error: The Release Mission is faild.

**Comment by hxhb** [comment]
4.21的引擎太老了，我已经没有这样的开发环境了，具体的问题你可以自己排查后给我提个PR。
