### ISSUE TITLE
发布基础版本会一直循环，发布补丁会无法生成release.json文件

### ISSUE THREAD

**Issue by gameiw** [hxhb/HotPatcher#60]
![image](https://user-images.githubusercontent.com/77440524/189345389-98c4bfb3-8c77-4d24-9525-7a7035f0083d.png)
![image](https://user-images.githubusercontent.com/77440524/189345472-6cc53d2f-9761-4393-a2e1-3727b88ac266.png)
 文件导出了，但是进程没有自动停止。
![image](https://user-images.githubusercontent.com/77440524/189345580-26ad19d6-0665-4d69-8c76-fdc186591bdb.png)
![image](https://user-images.githubusercontent.com/77440524/189346856-a39d7ca2-a8d1-4227-ac9f-493763425f4f.png)
发布补丁无法生成release.json文件
![image](https://user-images.githubusercontent.com/77440524/189346929-e7c07c96-2861-4bcd-9ff5-c34670bc2a2d.png)
进程也无法自动停止
![image](https://user-images.githubusercontent.com/77440524/189347016-64d2393d-caf5-4a59-996d-5fbac165d60e.png)

**Comment by Za0Shu1** [comment]
这个问题修复了没

**Comment by hxhb** [comment]
在UE5.0.3中测试未复现，提供更多信息后可以Repoen。

**Comment by TroutZhang** [comment]
@hxhb  遇到同样的问题，  v76.3 with UE 5.0.3。 Reopen 这个issue吧。

第一个小问题ByRelease的，我这里注释代码绕开解决了，是**http请求没处理完一直在模块 http卸载的时候等待**导致的。 你的请求版本信息的 http request能执行完，但是另外一个注册项目信息的我这里执行不完，所以就一直卡那里了。
注释掉的代码如下
![image](https://github.com/hxhb/HotPatcher/assets/3135621/52d54ad4-7d4f-42a7-ba86-f1ed3550aedd)

第二个小问题ByPatch的，我这里发现是因为所有线程都在sleep wait， 正在进一步调试中。
callstack如下：
![image](https://github.com/hxhb/HotPatcher/assets/3135621/c532467b-5aa6-4172-baf9-716e3197c368)

**Comment by TroutZhang** [comment]
第二个小问题关于 **ByPatch**的，已经**修复在  PR #86** ,  本质上是因为**原来的代码只是在用Sleep等，而没有去"tick" 异步任务，导致无限期的白等下去，永远不会结束**。 

具体在我的关卡改动后的patch-cook流程里，表现为是StaticMesh的 IsCompile永远为true导致Object->IsCachedCookedPlatformDataLoaded(TargetPlatform)也永远为true。

* 我的修复代码是参考了引擎的UDerivedDataCacheCommandlet 相关代码调用流程后改出来的。

**Comment by TroutZhang** [comment]
第一个小问题关于**ByRelease**的，因为其实Release的json是生成完毕的，只是进程退出时候卡在永不结束的一个我觉得不重要的http request上，所以没有深究下去，仅仅是如上回复中的图片那样注释了，也就没有提PR。

第二个小问题关于**ByPatch**的，则是因为需要的*_P.pak都没生成出来，所以才去调试修复了。

**Comment by TroutZhang** [comment]
@gameiw @Za0Shu1  如果你们还有类似问题，可以试试我的PR。
