### ISSUE TITLE
76.3 ue5.0.3 打包报错

### ISSUE THREAD

**Issue by yajunjiao** [hxhb/HotPatcher#63]
UATHelper: Packaging (Windows): ERROR: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
UATHelper: Packaging (Windows):        (referenced via Target -> CmdHandler.Build.cs)
PackagingResults: Error: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.

**Comment by hxhb** [comment]
可以把CmdHandler这个模块改成Editor的。

**Comment by yajunjiao** [comment]
这个问题解决了，先关掉吧，还有一些其他的问题，先研究下，试试解决方案
