### ISSUE TITLE
UE5.0.3默认的第三人称模板，打包关卡出错

### ISSUE THREAD

**Issue by livingyang** [hxhb/HotPatcher#68]
使用v77.0版本插件，复现步骤：
1. 新建一个第三人称模板的项目
2. 直接打包ThirdPersonExampleMap到windows平台
3. 然后会出现报错的日志

**Comment by yajunjiao** [comment]
打的是shipping 吗?

**Comment by hxhb** [comment]
已定位到问题，目前插件暂不支持WP的地图打包，后续会增加支持。

**Comment by CoderJackLiu** [comment]
wp指的是windows平台吗？

**Comment by hxhb** [comment]
> wp指的是windows平台吗？

World Partition

**Comment by CoderJackLiu** [comment]
UE5.0.3同样出现打包出错问题，不知道怎么操作才可以打包成功。打包成功后，用的是byRelease。会出现报错。如下：
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/26760292/200235439-af4c4db9-8179-489e-ad79-c707beb659d9.png">

求大佬指教

**Comment by hxhb** [comment]
发完整的Log

**Comment by hxhb** [comment]
#61
