### ISSUE TITLE
UE5.0.2 Version v77.0 热更新上去的pak使用软引用路径找不到资源

### ISSUE THREAD

**Issue by jiayueshiliuqi** [hxhb/HotPatcher#70]
我打好一个基础版本并且导出release以后，在Content下创建了一个Test文件夹，然后导入了一个骨骼网格体，然后用刚刚生成的release打了一个新的pak，放到Windows/xxx/Content/Pak里以后启动应用程序，利用软路径加载刚刚导入的网格体(SkeletalMesh'/Game/Test/f_tal_unw_top.f_tal_unw_top')，说找不到
LogStreaming: Warning: LoadPackage: SkipPackage: /Game/Test/f_tal_unw_top(0xB9942B520D383582) - The package to load does not exist on disk or in the loader

pak包应该是正确被挂载上了？
LogPakFile: Display: Found Pak file ../../../xxx/Content/Paks/beta0.2_Windows_001_P.pak attempting to mount.
LogPakFile: Display: Mounting pak file ../../../xxx/Content/Paks/beta0.2_Windows_001_P.pak.
LogPakFile: Warning: IoStore container "../../../xxx/Content/Paks/beta0.2_Windows_001_P.utoc" not found
LogPakFile: Display: Mounted Pak file '../../../xxx/Content/Paks/beta0.2_Windows_001_P.pak', mount point: '../../../xxx/Content/Test/'

这个是我有什么配置不正确吗？

**Comment by hxhb** [comment]
挂载失败了，关闭项目设置中的IoStore
