### ISSUE TITLE
Mods repositories are empty.

### ISSUE THREAD

**Issue by jihwanahn** [hxhb/HotPatcher#74]
Hi,

I tried to pull the repository with git bash, and it prints the message below.
Could you please check with it?

Thank you in advance :)

`Cloning into 'C:/Work/gitlab/HotPatcher/Mods/HDiffPatchUE'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hxhb/HDiffPatchUE.git' into submodule path 'C:/Work/gitlab/HotPatcher/Mods/HDiffPatchUE' failed
Failed to clone 'Mods/HDiffPatchUE'. Retry scheduled
Cloning into 'C:/Work/gitlab/HotPatcher/Mods/HotChunker'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hxhb/HotChunker.git' into submodule path 'C:/Work/gitlab/HotPatcher/Mods/HotChunker' failed
Failed to clone 'Mods/HotChunker'. Retry scheduled
Cloning into 'C:/Work/gitlab/HotPatcher/Mods/HotMultiCooker'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hxhb/HotMultiCooker.git' into submodule path 'C:/Work/gitlab/HotPatcher/Mods/HotMultiCooker' failed
Failed to clone 'Mods/HotMultiCooker'. Retry scheduled
Cloning into 'C:/Work/gitlab/HotPatcher/Mods/RemakePak'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hxhb/RemakePak.git' into submodule path 'C:/Work/gitlab/HotPatcher/Mods/RemakePak' failed
Failed to clone 'Mods/RemakePak'. Retry scheduled
Cloning into 'C:/Work/gitlab/HotPatcher/Mods/libzstd'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hxhb/ue-zstd.git' into submodule path 'C:/Work/gitlab/HotPatcher/Mods/libzstd' failed
Failed to clone 'Mods/libzstd'. Retry scheduled
Cloning into 'C:/Work/gitlab/HotPatcher/Mods/HDiffPatchUE'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hxhb/HDiffPatchUE.git' into submodule path 'C:/Work/gitlab/HotPatcher/Mods/HDiffPatchUE' failed
Failed to clone 'Mods/HDiffPatchUE' a second time, aborting
`

**Comment by hxhb** [comment]
These modules are currently not open, and failure to pull them will not have any impact on the hot update function.
