### ISSUE TITLE
模型nanite后，hotpatcher-80版本打包pak，加载报错

### ISSUE THREAD

**Issue by fengdays** [hxhb/HotPatcher#75]
模型nanite后，5.1 hotpacher 打包pak，加载报错  Assertion failed: !HasStreamingData() || StreamablePages.GetBulkDataSize() > 0 [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Rendering\NaniteResources.cpp] [Line: 270]

报错地方   #if !WITH_EDITOR
		check(!HasStreamingData() || StreamablePages.GetBulkDataSize() > 0);
#endif
	}

mesh数据自己打到exe里测试没问题

**Comment by Zikyaai99** [comment]
我也遇到了这个问题，大佬你解决了吗

**Comment by hxhb** [comment]
要使用最新版本
