### ISSUE TITLE
新Patcher的Release.json文件内包含了资源改径前后的路径(存在2份)

### ISSUE THREAD

**Issue by hbdjzwl** [hxhb/HotPatcher#8]
步骤1 : 当by release->   打包一个基础包的时候出现一个指定目录的所有资源文件的Base1.0_Release.json文件。

步骤2 : 在编辑器里，将A目录的蓝图资源，移动到B目录去(重定向与不重定向都已尝试，也保存了)。

步骤3 : 当by patcher->  打包一个补丁包时，基于Base1.0Release.json打包新包生成的Patcher1.1_Release.json文件时。

【问题所在】 : 该Patcher1.1_Release.json的资源路径里包含了该资源的2份路径，分别是移动前与移动后。
文件:Patcher1.1_Release.json
{
      旧路径: "/Game/Blueprint/NewBlueprint":  {...}
      新路径: "/Game/Geometry/NewBlueprint": {...}
}

需要注意的是:新路径是在
				"moduleCategory": "Game",
				"assetDependencyDetails":
				{
                                  ........
                                }
该分类的最下方。

;------------------------------------上方问题导致的延续问题----------------------------------------
当打包新的包时会基于上一个版本的release.json里的所有资源进行比较。
当发现上一个版本有一个 新路径和旧路径的资源时。判断当前版本没有老版本的旧路径资源(当前磁盘不存在)
就判定在当前版本里diff.json文件里。delete 分类下{} 就包含了这个旧资源路径被删除。

**Comment by hxhb** [comment]
已支持，可以通过控制`bSaveDeletedAssetToNewReleaseJson`来决定在ContentBrowser中的资源是否保存至新的Release.Json中，更新master分支至[c3356ba](https://github.com/hxhb/HotPatcher/commit/c3356ba8339ca4747119700f0c6b7fd25d4557de)即可。
