### ISSUE TITLE
其他插件没有被打包进去

### ISSUE THREAD

**Issue by DZTZ** [hxhb/HotPatcher#85]
我新加入了一个插件，但是打包后，新插件效果没生效，
新加的插件应该没有被打进去，是需要什么特殊设置吗？

**Comment by hxhb** [comment]
不要提与项目无关的issue

**Comment by DZTZ** [comment]
大哥你可能没理解我的意思，请让我再解释一下。
我的问题是在使用HotPatcher进行打包的时候，发现其他的插件没有被打进去，想知道为什么，其他的插件指的是增加了一个http请求的插件。

**Comment by DZTZ** [comment]
> 不要提与项目无关的issue

大哥你可能没理解我的意思，请让我再解释一下。
我的问题是在使用HotPatcher进行打包的时候，发现其他的插件没有被打进去，想知道为什么，其他的插件指的是增加了一个http请求的插件。

**Comment by DZTZ** [comment]
> 不要提与项目无关的issue

文档中有提到，不能热更新C++，那么我新增的插件如果是C++编写的是不是就不能被打包进去？
麻烦大佬解答下，谢谢

**Comment by hxhb** [comment]
是的
