### ISSUE TITLE
v81 使用UE5.0.3 不能编译

### ISSUE THREAD

**Issue by yaoyutian** [hxhb/HotPatcher#87]
已启动生成...
1>------ 已启动生成: 项目: P_Bin_CS, 配置: Development_Editor x64 ------
1>Using bundled DotNet SDK
1>Log file: C:\Users\yaodn\AppData\Local\UnrealBuildTool\Log.txt
1>Creating makefile for P_Bin_CSEditor (no existing makefile)
1>UnrealBuildTool : warning : The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\HotPatcher.uplugin : warning : The 'Developer' module type has been deprecated in 4.24.
1>MajorVersion 5 MinorVersion: 0 PatchVersion 3
1>MajorVersion 5 MinorVersion: 0 PatchVersion 3
1>Building P_Bin_CSEditor...
1>Using Visual Studio 2022 14.36.32532 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.36.32532) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>[Adaptive Build] Excluded from BinariesPatchFeature unity file: BinariesPatchFeature.cpp
1>[Adaptive Build] Excluded from CmdHandler unity file: CmdHandler.cpp
1>[Adaptive Build] Excluded from P_Bin_CS unity file: P_Bin_CS.cpp, P_Bin_CSCharacter.cpp, P_Bin_CSGameMode.cpp, P_Bin_CSProjectile.cpp, TP_PickUpComponent.cpp, TP_WeaponComponent.cpp
1>Determining max actions to execute in parallel (8 physical cores, 16 logical cores)
1>  Executing up to 8 processes, one per physical core
1>Building 8 actions with 8 processes...
1>[1/8] Compile Module.HotPatcherRuntime.cpp
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(314): error C2664: “FAssetData IAssetRegistry::GetAssetByObjectPath(const FName,bool) const”: 无法将参数 1 从“FSoftObjectPath”转换为“const FName”
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(316): note: 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
1>D:\Unreal\UE_5.0\Engine\Source\Runtime\AssetRegistry\Public\AssetRegistry\IAssetRegistry.h(210): note: 参见“IAssetRegistry::GetAssetByObjectPath”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(314): note: 尝试匹配参数列表“(FSoftObjectPath, bool)”时
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(335): error C2664: “FAssetData IAssetRegistry::GetAssetByObjectPath(const FName,bool) const”: 无法将参数 1 从“FSoftObjectPath”转换为“const FName”
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(337): note: 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
1>D:\Unreal\UE_5.0\Engine\Source\Runtime\AssetRegistry\Public\AssetRegistry\IAssetRegistry.h(210): note: 参见“IAssetRegistry::GetAssetByObjectPath”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(335): note: 尝试匹配参数列表“(FSoftObjectPath, bool)”时
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(493): error C2664: “FAssetData IAssetRegistry::GetAssetByObjectPath(const FName,bool) const”: 无法将参数 1 从“FSoftObjectPath”转换为“const FName”
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(495): note: 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
1>D:\Unreal\UE_5.0\Engine\Source\Runtime\AssetRegistry\Public\AssetRegistry\IAssetRegistry.h(210): note: 参见“IAssetRegistry::GetAssetByObjectPath”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(493): note: 尝试匹配参数列表“(FSoftObjectPath, bool)”时
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherRuntime\Private\FlibAssetManageHelper.cpp(1277): warning C4996: 'LoadPackageAsync': Use version that takes a FPackagePath without a FGuid Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>[2/8] Compile Module.HotPatcherCore.cpp
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(88): error C2065: “FPackageHashes”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(88): error C2923: "TRefCountPtr": "FPackageHashes" 不是参数 "ReferencedType" 的有效 模板 类型参数
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(88): note: 参见“FPackageHashes”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(88): error C3203: "TRefCountPtr": 未指定的 类 模板 不能用作 模板 参数 "InValueType" 的 模板 参数，应为真实类型
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(93): error C2065: “FPackageHashes”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(93): error C2923: "TRefCountPtr": "FPackageHashes" 不是参数 "ReferencedType" 的有效 模板 类型参数
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(93): note: 参见“FPackageHashes”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(93): error C3203: "TRefCountPtr": 未指定的 类 模板 不能用作 模板 参数 "InValueType" 的 模板 参数，应为真实类型
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(35): error C2555: “FHotPatcherPackageWriter::CommitPackageInternal”: 重写虚函数返回类型有差异，且不是来自“TPackageWriterToSharedBuffer<ICookedPackageWriter>::CommitPackageInternal”的协变
1>D:\Unreal\UE_5.0\Engine\Source\Runtime\CoreUObject\Internal\Serialization\PackageWriterToSharedBuffer.h(129): note: 参见“TPackageWriterToSharedBuffer<ICookedPackageWriter>::CommitPackageInternal”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.h(88): error C3668: “FHotPatcherPackageWriter::GetPackageHashes”: 包含重写说明符“override”的方法没有重写任何基类方法
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.cpp(248): error C2039: "Status": 不是 "IPackageWriter::FCommitPackageInfo" 的成员
1>D:\Unreal\UE_5.0\Engine\Source\Runtime\Core\Public\Serialization\PackageWriter.h(76): note: 参见“IPackageWriter::FCommitPackageInfo”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.cpp(248): error C2653: “ECommitStatus”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotPatcherPackageWriter.cpp(248): error C2065: “Success”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(22): error C2061: 语法错误: 标识符“ETeardown”
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(46): error C3646: “CookContext”: 未知重写说明符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(46): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(22): error C3668: “FHotWorldPartitionCookPackageSplitter::Teardown”: 包含重写说明符“override”的方法没有重写任何基类方法
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(25): error C3668: “FHotWorldPartitionCookPackageSplitter::PopulateGeneratedPackage”: 包含重写说明符“override”的方法没有重写任何基类方法
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(27): error C3668: “FHotWorldPartitionCookPackageSplitter::PopulateGeneratorPackage”: 包含重写说明符“override”的方法没有重写任何基类方法
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.h(30): error C3668: “FHotWorldPartitionCookPackageSplitter::OnOwnerReloaded”: 包含重写说明符“override”的方法没有重写任何基类方法
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(35): error C2065: “ETeardown”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(35): error C2146: 语法错误: 缺少“)”(在标识符“Status”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(36): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(36): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(105): error C2039: "BeginCook": 不是 "UWorldPartition" 的成员
1>D:\Unreal\UE_5.0\Engine\Source\Runtime\Engine\Public\WorldPartition\WorldPartitionSubsystem.h(9): note: 参见“UWorldPartition”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(105): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(108): error C2065: “IWorldPartitionCookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(108): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(108): error C2143: 语法错误: 缺少“;”(在“:”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(108): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(108): error C2143: 语法错误: 缺少“;”(在“)”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(110): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(110): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(113): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(113): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(113): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(113): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(118): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(118): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(118): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(127): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(127): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(127): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(127): error C2653: “FWorldPartitionCookPackage”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(127): error C2039: "GeneratedRootPath": 不是 "ICookPackageSplitter::FGeneratedPackageForPopulate" 的成员
1>D:\Unreal\UE_5.0\Engine\Source\Editor\UnrealEd\Public\CookPackageSplitter.h(50): note: 参见“ICookPackageSplitter::FGeneratedPackageForPopulate”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(127): error C3861: “MakeGeneratedFullPath”: 找不到标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(131): error C2065: “IWorldPartitionCookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(131): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(132): error C2065: “FWorldPartitionCookPackage”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(132): error C2065: “CookPackage”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(134): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(134): error C2039: "GeneratedRootPath": 不是 "ICookPackageSplitter::FGeneratedPackageForPopulate" 的成员
1>D:\Unreal\UE_5.0\Engine\Source\Editor\UnrealEd\Public\CookPackageSplitter.h(50): note: 参见“ICookPackageSplitter::FGeneratedPackageForPopulate”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(134): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(134): error C2065: “CookPackage”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(136): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(136): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(136): error C2065: “CookPackage”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(140): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(140): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(140): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(140): error C2653: “FWorldPartitionCookPackage”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(140): error C2039: "GeneratedRootPath": 不是 "ICookPackageSplitter::FGeneratedPackageForPopulate" 的成员
1>D:\Unreal\UE_5.0\Engine\Source\Editor\UnrealEd\Public\CookPackageSplitter.h(50): note: 参见“ICookPackageSplitter::FGeneratedPackageForPopulate”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(140): error C3861: “MakeGeneratedFullPath”: 找不到标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(144): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(144): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(144): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(144): error C2653: “FWorldPartitionCookPackage”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(144): error C2039: "GeneratedRootPath": 不是 "ICookPackageSplitter::FGeneratedPackageForPopulate" 的成员
1>D:\Unreal\UE_5.0\Engine\Source\Editor\UnrealEd\Public\CookPackageSplitter.h(50): note: 参见“ICookPackageSplitter::FGeneratedPackageForPopulate”的声明
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(144): error C3861: “MakeGeneratedFullPath”: 找不到标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(154): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(154): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(154): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(157): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(159): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(159): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(159): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(159): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(164): error C2065: “IWorldPartitionCookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(164): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(164): error C2143: 语法错误: 缺少“;”(在“:”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(164): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(164): error C2143: 语法错误: 缺少“;”(在“)”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(166): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(166): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(167): error C2065: “FWorldPartitionCookPackage”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(167): error C2059: 语法错误:“>”
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(167): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(167): error C2062: 意外的类型“unknown-type”
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(168): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(169): error C2065: “CookPackageGenerator”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(169): error C2065: “CookContext”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(169): error C2065: “CookPackages”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(173): error C2653: “FLogCategoryLogHotWorldPartition”: 不是类或命名空间名称
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(173): error C2065: “CompileTimeVerbosity”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(173): error C2065: “LogHotWorldPartition”: 未声明的标识符
1>D:\Unreal\P_Bin_CS\Plugins\HotPatcher\Source\HotPatcherCore\Private\Cooker\PackageWriter\HotWorldPartitionCookPackageSplitter.cpp(173): fatal error C1003: 错误计数超过 100；正在停止编译
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: 命令“D:\Unreal\UE_5.0\Engine\Build\BatchFiles\Build.bat P_Bin_CSEditor Win64 Development -Project="D:\Unreal\P_Bin_CS\P_Bin_CS.uproject" -WaitMutex -FromMsBuild”已退出，代码为 6。
1>已完成生成项目“P_Bin_CS.vcxproj”的操作 - 失败。
========== 生成: 0 成功，1 失败，0 最新，0 已跳过 ==========
========= 生成 开始于 3:36 PM，并花费了 11.157 秒 ==========

**Comment by hxhb** [comment]
5.0.3只能用v77

**Comment by yaoyutian** [comment]
OK，不过release里好像没写对应支持的UE版本

**Comment by hxhb** [comment]
[UE5+的问题排查](https://imzlp.com/posts/16895/#UE5-%E7%9A%84%E9%97%AE%E9%A2%98%E6%8E%92%E6%9F%A5)
