### ISSUE TITLE
5.3.2，当只修改一个蓝图，打patch运行后会崩溃。发现的解决方案是：将引用该AssetItem的上层文件和引用上层文件的Map也加入到打包列表中，可以正常运行

### ISSUE THREAD

**Issue by wuchunpeng777** [hxhb/HotPatcher#98]

**Comment by wuchunpeng777** [comment]
比如一个场景里边放了一个actor蓝图，修改这个actor蓝图，比如内部加个cube。打patch时候，差异只有actor蓝图一个文件，打patch后，加载运行，打开这个场景的时候会崩溃。如果打patch时同时把这个没有变化的场景打进去，则运行后不会崩溃

**Comment by hxhb** [comment]
未复现该崩溃问题。但对于WP的分析逻辑需要进行扩展，详见[补充资料](https://imzlp.com/posts/16808/#%E8%A1%A5%E5%85%85%E8%B5%84%E6%96%99)。

**Comment by wuchunpeng777** [comment]
https://github.com/wuchunpeng777/HotPatcher_V82_Bug_Recurrent
结构如下
1.TestA和TestB是BaseActor的子类
2.MapA场景里放了TestA，MapB场景里放了TestB

步骤如下
1.目录默认/Game全部
2.直接生成release信息1_Release.json
3.修改BaseActor点击保存
4.patch模式以1_Release.json为基础，预览差异，只有BaseActor。即使点击SaveAll后也是只有BaseActor，这样打出的包会崩溃
5.只有手动找到MapA、MapB、TestA、TestB，挨个点保存，再预览差异，列表中才会有这些文件，打出的包才能正常

**Comment by hxhb** [comment]
已知，补充资料里写了，这个问题会在下个版本解决。

**Comment by wuchunpeng777** [comment]
> 已知，补充资料里写了，这个问题会在下个版本解决。

好的
